function out1 = spgrJacobian(R1,R2,TEspgr,TRspgr,alpha_spgr,b1,iM0,rM0)
%SPGRJACOBIAN
%    OUT1 = SPGRJACOBIAN(R1,R2,TESPGR,TRSPGR,ALPHA_SPGR,B1,IM0,RM0)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    20-Sep-2017 12:14:33

t2 = alpha_spgr.*b1;
t9 = R1.*TRspgr;
t3 = exp(-t9);
t4 = iM0.*1i;
t5 = rM0+t4;
t6 = sign(t5);
t15 = R2.*TEspgr;
t7 = exp(-t15);
t8 = sin(t2);
t10 = cos(t2);
t11 = t3.*t10;
t12 = t11-1.0;
t13 = 1.0./t12;
t14 = t3-1.0;
t16 = abs(t5);
t17 = exp(t9);
out1 = [t6.*t7.*t8.*t13.*t14,t6.*t7.*t8.*t13.*t14.*1i,-TRspgr.*t3.*t7.*t8.*t13.*t16+TRspgr.*t3.*t7.*t8.*t10.*1.0./t12.^2.*t14.*t16,-TEspgr.*t7.*t8.*t13.*t14.*t16,-alpha_spgr.*t16.*exp(-t9-R2.*TEspgr.*2.0).*(exp(t9+t15)-t10.*exp(t15+R1.*TRspgr.*2.0)).*1.0./(t10-t17).^2.*(t17-1.0)];
